import json
from typing import Any
from urllib.parse import urlparse

import requests
from git import Repo
from github import Github

from config import settings


def _authenticated_remote_url(repo_url: str, token: str) -> str:
    parsed = urlparse(repo_url)
    return f"https://{token}@{parsed.netloc}{parsed.path}"


def _build_pr_body(state: dict[str, Any]) -> str:
    test_result = state.get("test_result", {})
    similar = state.get("similar_issues", [])
    similar_lines = "\n".join(
        f"- [{s['issue_key']}] {s['summary']} (score: {s['score']})" for s in similar
    ) or "_None_"

    failed_tests = test_result.get("failed_tests", [])
    test_summary = "All tests passed." if test_result.get("passed") else (
        "Test failures:\n```\n" + "\n".join(failed_tests[:10]) + "\n```"
    )

    return f"""## AI-Generated Fix for {state['issue_key']}

### Bug Summary
{state.get('summary', '')}

### Description
{state.get('description', '')[:500]}

### Fix Description
{state.get('fix_description', '_No description provided_')}

### Test Results
{test_summary}

### Similar Issues Referenced (via RAG)
{similar_lines}

### Files Modified
{chr(10).join(f'- `{f}`' for f in state.get('relevant_files', [])) or '_None tracked_'}

---
> Generated by Multi-Agent Bug Resolver · Requires human review before merge.
"""


def _notify_slack(pr_url: str, issue_key: str, summary: str) -> None:
    payload = {
        "text": f":robot_face: *AI Fix Ready for Review*\n"
                f"Issue: `{issue_key}` — {summary}\n"
                f"PR: {pr_url}\n"
                f"Please review and approve or close."
    }
    try:
        resp = requests.post(settings.slack_webhook_url, json=payload, timeout=10)
        resp.raise_for_status()
        print("[pr_creator] Slack notification sent")
    except Exception as exc:
        print(f"[pr_creator] Slack notification failed: {exc}")


def run(state: dict[str, Any]) -> dict[str, Any]:
    issue_key = state["issue_key"]
    summary = state.get("summary", "")
    repo_path = state["repo_path"]
    branch = f"fix/ai-{issue_key}"

    print(f"[pr_creator] Committing and pushing branch '{branch}' ...")

    repo = Repo(repo_path)
    repo.git.add("-A")

    commit_msg = f"fix(ai): resolve {issue_key} — {summary[:60]}"
    repo.index.commit(commit_msg)

    auth_url = _authenticated_remote_url(settings.repo_url, settings.github_token)
    origin = repo.remotes[0] if repo.remotes else repo.create_remote("origin", auth_url)
    origin.set_url(auth_url)
    origin.push(refspec=f"{branch}:{branch}")
    print(f"[pr_creator] Pushed branch {branch}")

    # Parse owner/repo from repo URL
    path_parts = urlparse(settings.repo_url).path.strip("/").replace(".git", "").split("/")
    owner, repo_name = path_parts[-2], path_parts[-1]

    gh = Github(settings.github_token)
    gh_repo = gh.get_repo(f"{owner}/{repo_name}")

    pr = gh_repo.create_pull(
        title=f"[AI Fix] {issue_key}: {summary}",
        body=_build_pr_body(state),
        base=settings.repo_default_branch,
        head=branch,
    )
    pr_url = pr.html_url
    print(f"[pr_creator] PR created: {pr_url}")

    if settings.slack_webhook_url:
        _notify_slack(pr_url, issue_key, summary)

    return {"pr_url": pr_url, "status": "AWAITING_APPROVAL"}
